config/routes.rb
MIF::Application.routes.draw do
   resources :cards do
    member do
      post 'worked'
    end
  end
  devise_for :users
 
  root 'cards#index'
  get "Cards" => "pages#cards"

   

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :user 
	has_attached_file :image, :styles => {:full => "auto", :large => "600x600>", :medium => "400x400>", :thumb => "150x150>"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates :image, presence: true
	validates :title, presence: true, length: {minimum: 3}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cards, dependent: :destroy
   validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
	devise_parameter_sanitizer.for(:account_update) << :name  
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
before_action :set_card, only: [:show, :edit, :update, :destroy, :worked]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


	def new
		@card = current_user.cards.build
	end	
	
	def index
		@cards =  Card.all.order("created_at DESC").paginate(:page => params[:page])
	end

	def show
		@card = Card.find(params[:id])
	end
	
	def edit
		@card = Card.find(params[:id])
	end

	def update
		@card = Card.find(params[:id])

		if @card.update(card_params)
			redirect_to @card, notice: 'Card was successfully updated.'
		else
			render action: 'edit'
		end
	end

	def create
		@card = current_user.cards.build(card_params)

		if @card.save
			redirect_to @card, notice: 'Card was successfully created'
		else
			render action: 'new'
		end
	end

	def destroy
		@card = Card.find(params[:id])
		@card.destroy

		redirect_to cards_path
	end

  def worked
    if @card.update_attribute(:worked, params[:worked])
      redirect_to @card, notice: 'Card was logged successfully'
    else
      render action: 'show'
    end
  end

	private
		def set_card
			@card = Card.find(params[:id])
		end
		def correct_user
      	@card = current_user.cards.find_by(id: params[:id])
      redirect_to cards_path, notice: "Not authorized to edit this Card" if @card.nil?
   		 end
		def card_params
				params.require(:card).permit(:title, :text, :image, :worked)
		end		
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/logcards_helper.rb
module LogcardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_form.html.erb
<%= form_for @card, html: {multipart: true} do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@card.errors.count, "error") %> prohibited
    this card from being saved:</h2>

    <ul>
    <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
 
  <div class="form-group">
     Describe this card
    <%= f.text_area :text, class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1> Editing Cards </h1>

<%= render 'form' %>
 
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<div id="cards" class="transitions-enabled">
  <% @cards.each do |card| %>
    <div class="box panel panel-default flip">
         <figure>
          <%= link_to image_tag(card.image.url(:medium)), card %>
          <figcaption>
                  <p>  Have you worked on this today?&nbsp;<p>
            <p><strong><%= link_to 'YES', worked_card_path(card, worked: true), method: :post, class: "btn btn-success btn-sm" %></strong>
            &nbsp;<%= link_to 'NO', worked_card_path(card, worked: false), method: :post, class: "btn btn-primary btn-sm" %><p>
          </figcaption>
        </figure>
        <div class="panel-body">
          <div class="panel-heading center">
            <div class="button">
              <p><strong><%= link_to card.title, :action => 'show', :id => card.id %></strong></p>
             </div>
            </div>
              
         </div>  
    </div>
  <% end %>
</div>

<div class="center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/cards/new.html.erb
<h1> New Card </h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<%= link_to cards_path do %>
<span class="glyphicon glyphicon-chevron-left"></span>
		Back
	<% end %>


<div class="row">
	<div class="col-md-offset-3 col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @card.image.url (:medium) %>
			</div>
	<div class="panel-body">
		<h2 align="center">
		<p>
		<%= @card.title %>
		</p>
		</h2>
		<h3>
		<p align="center">
		<%= @card.text %>
		</p>
		</h3>
		<br>
<% if current_user && (@card.user == current_user) %>


            <div>
                <p align="center">
                    Have you worked on this today?</p>
                    <p align="center">
                    <%= link_to 'YES', worked_card_path(@card, worked: true), method: :post, class: "btn btn-success btn-sm" %>
                    
                    <%= link_to 'NO', worked_card_path(@card, worked: false), method: :post, class: "btn btn-primary btn-sm" %>
                   </p>
                </div>
            </div>
        </br>
            <%= link_to edit_card_path(@card) do %>
                    <span class="glyphicon glyphicon-pushpin"></span>
                    Edit
                  <% end %>
	<%= link_to @card, method: :delete, data: { confirm: 'Are you sure?' } do %>
             <span class="glyphicon glyphicon-trash"></span>
              Delete
             <% end %>	
<% end %>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Move It Forward", root_path, class: "navbar-brand" %>
    </div>
     
     <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
        <li class="container-fluid"><%= link_to "Home", root_path %></li>
        <li class="container-fluid"><%= link_to "Cards", cards_path %></li>
        <% if user_signed_in? %>
          <li class="container-fluid">
              <%= link_to new_card_path do %>
                  
                    <span class="glyphicon glyphicon-plus"></span> 
                     New Card
                <% end %>
            </li>
        <li class="container-fluid"><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li class="container-fluid"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li class="container-fluid"><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Move It Forward</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			 <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
<h1> Move It Forward!</h1>

<h2> Day by day, brick by brick</h2>
<p>
<% link_to 'My Cards', controller: 'cards' %>
<%= link_to "Log in", new_user_session_path , class: "btn btn-default btn-lg" %>
<%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1> Move It Forward!</h1>

<h2> Day by day, brick by brick</h2>
<p>
<% link_to 'My Cards', controller: 'cards' %>
<%= link_to "Log in", new_user_session_path , class: "btn btn-default btn-lg" %>
<%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
</p>

</div>